### ISSUE TITLE
Feature Request - Add a locate myself button

### ISSUE THREAD

**Issue by hayschan** [meshtastic/meshtastic_linkplanner#11]
Currently, users have to scroll through the world map to finally reach their own place to do planning on the map.

It would be extremely easy for users if there is a locate myself button on the side, just like any other map tools. This will locate the interested area promptly.

![image](https://github.com/user-attachments/assets/ffdb518f-c380-44e0-9fd1-3cbc6434d055)

**Comment by mrpatrick1991** [comment]
Sounds good - I like it.

**Comment by mrpatrick1991** [comment]
Deployed in https://github.com/meshtastic/meshtastic_linkplanner/commit/0ba3f3ebf42cd4941b646a5ceae0af43c94f799c

Clear the browser cache and reload the hosted version to see. The control is in the upper left hand corner near the layer selector.

**Comment by hayschan** [comment]
> Deployed in [0ba3f3e](https://github.com/meshtastic/meshtastic_linkplanner/commit/0ba3f3ebf42cd4941b646a5ceae0af43c94f799c)
> 
> Clear the browser cache and reload the hosted version to see. The control is in the upper left hand corner near the layer selector.

Great job. Love it. Thank you so much for your effort.
