### ISSUE TITLE
[Feature Request]  Clarification on height variable

### ISSUE THREAD

**Issue by Nitrousoxide** [meshtastic/meshtastic_linkplanner#8]
Something that isn't entirely clear to me is whether the height variable should be entered as the relative height above the ground at the given coordinates, or the absolute height above sea level.  A mouseover info bubble clarifying this for the user might be a nice addition.

The readme seems to indicate it's relative to the ground at the given coordinates, but this isn't apparent on the hosted page.

**Comment by mrpatrick1991** [comment]
I agree, good idea. I'll add something this week.

**Comment by mrpatrick1991** [comment]
Added in https://github.com/meshtastic/meshtastic_linkplanner/commit/11933034cb7cd211eade1a44ced9f2e25003cd12
